# Generated by Django 3.1.3 on 2021-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_due', models.DateField()),
                ('task_title', models.CharField(max_length=50)),
                ('task_hint', models.CharField(max_length=10)),
                ('task_description', models.CharField(max_length=150)),
            ],
        ),
    ]
